---
- hosts: target
  gather_facts: no
  tasks:
    - name: Update yum package manager repositories cache
      become: true
      yum:
        name: '*'
        state: latest
        update_cache: yes
    - name: Install python3 using Ansible
      become: yes
      dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - python3
